spring:
  application:
    name: spring-template

  datasource:
    url: jdbc:mysql://localhost:3306/javacrud
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10        # Max connections in pool
      minimum-idle: 5              # Minimum idle connections
      idle-timeout: 30000          # 30 sec
      max-lifetime: 1800000        # 30 min
      connection-timeout: 20000    # 20 sec
      pool-name: HikariCP

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # This will automatically update the schema

server:
  port: 8080
